import { Bill } from "../types/bill.types";

export const CATEGORIES = [
  "All",
  "Taxation",
  "Finance",
  "Privacy",
  "Technology",
  "Agriculture",
  "Healthcare",
  "Education",
  "Labour",
  "Environment",
];

export const STATUSES: Bill["status"][] = [
  "Introduced",
  "Committee",
  "Lok Sabha",
  "Rajya Sabha",
  "Assented",
  "Implemented",
];

export const SEEDED_BILLS: Bill[] = [
  {
    id: 1,
    title: "The Finance Bill, 2024",
    shortTitle: "Finance Bill 2024",
    billNumber: "Bill No. 112 of 2024",
    year: 2024,
    category: "Taxation",
    status: "Implemented",
    summary: "Revises personal income tax slab thresholds, increases standard deduction from ₹50,000 to ₹75,000, and modifies capital gains tax framework.",
    ministry: "Ministry of Finance",
    introducedDate: "23 Jul 2024",
    effectiveDate: "01 Apr 2024",
    readingTime: 4,
    pages: 412,
    language: "English",
    pdfUrl: "/documents/finance_bill_2024.pdf",
    thumbnail: "/assets/bills/finance_2024.png",
    confidence: 98,
    ruleCount: 198,
    clauseCount: 2148,
    impactCategories: ["Salary", "Capital Gains", "Pensions"],
  },
  {
    id: 2,
    title: "The Digital Personal Data Protection Act, 2023",
    shortTitle: "DPDP Act 2023",
    billNumber: "Bill No. 156 of 2023",
    year: 2023,
    category: "Privacy",
    status: "Implemented",
    summary: "Establishes a statutory framework for digital personal data processing, compliance penalties up to ₹250 Cr, and Data Principal rights.",
    ministry: "MeitY",
    introducedDate: "11 Aug 2023",
    effectiveDate: "12 Aug 2023",
    readingTime: 6,
    pages: 48,
    language: "English",
    pdfUrl: "/documents/dpdp_act_2023.pdf",
    thumbnail: "/assets/bills/dpdp_2023.png",
    confidence: 99,
    ruleCount: 42,
    clauseCount: 44,
    impactCategories: ["Digital Privacy", "Corporate Penalty", "Consent"],
  },
  {
    id: 3,
    title: "Capital Gains Tax Exemption Revision Bill",
    shortTitle: "Capital Gains Amendment",
    billNumber: "Bill No. 89 of 2024",
    year: 2024,
    category: "Finance",
    status: "Committee",
    summary: "Proposes changes to Long Term Capital Gains (LTCG) holding periods for real estate, listed equity, and unlisted securities.",
    ministry: "Ministry of Finance",
    introducedDate: "23 Jul 2024",
    readingTime: 3,
    pages: 64,
    language: "English",
    pdfUrl: "/documents/capital_gains_2024.pdf",
    thumbnail: "/assets/bills/capital_gains.png",
    confidence: 96,
    ruleCount: 34,
    clauseCount: 120,
    impactCategories: ["Real Estate", "Mutual Funds", "LTCG"],
  },
  {
    id: 4,
    title: "The Telecommunications Act, 2023",
    shortTitle: "Telecom Act 2023",
    billNumber: "Bill No. 180 of 2023",
    year: 2023,
    category: "Technology",
    status: "Implemented",
    summary: "Consolidates laws relating to telecommunication services, spectrum assignment, security, and right-of-way permissions.",
    ministry: "Ministry of Communications",
    introducedDate: "18 Dec 2023",
    readingTime: 5,
    pages: 82,
    language: "English",
    pdfUrl: "/documents/telecom_2023.pdf",
    thumbnail: "/assets/bills/telecom.png",
    confidence: 97,
    ruleCount: 56,
    clauseCount: 210,
    impactCategories: ["Telecom Users", "Spectrum Licensing"],
  },
];
